### ISSUE TITLE
EEZ flow: Rounding of float behaviour in text labels is inconsistent 

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#196]
Using Math.round() in a text label doesn't work as I would expect. The behaviour between double and float is also different.

Example flow:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/8796121/184553896-a52705a7-42e9-4dd2-9e51-713d339b6889.png">

Will result in (after final breakpoint):
<img width="898" alt="image" src="https://user-images.githubusercontent.com/8796121/184553919-a8667d44-dc12-42d0-a0b2-9ea3128302ca.png">

The B row float seems out of oder. The other values look ok to me.

Using 0.9.94 on Mac M1.

Project file:
[RoundTest.eez-project.zip](https://github.com/eez-open/studio/files/9334075/RoundTest.eez-project.zip)

**Comment by fietser28** [comment]
I encountered a possibly similar/same problem in the SCPI component/commands:

If I send a float to the SCPI command with a value of 0.25 then 'inf' is send to the BB3 (according to the debug log). I seems some values like 0, 1, 2 work but with some fractions not. I can't find a pattern in this.

My workaround is similar as with the text component (setval is a string):
![image](https://user-images.githubusercontent.com/8796121/184600780-1adf428d-a916-400e-8612-43d5a7477ef9.png)

**Comment by mvladic** [comment]
Please test the latest build and let me know if `'inf'` bug is fixed.

**Comment by mvladic** [comment]
We have `float` and `double` type because for embedded use `double` could be too expensive performance wise. General advice for dashboards is to use `double` to prevent any rounding errors when converting `float` to `double`, because `double` (i.e. number) is only type that JavaScript knows.

Let me expain why `Math.round(offset, 2)` differs from `Math.round(offset, 2) + ""`. These two expressions are evaluated inside engine (engine knows how to work with both `float` and `double`!). Former expresssion results in value of `float` type, and later result in value of string type (properly rounded to two decimal digits inside engine and converted to string value for use inside JavaScript). When result value of former expression is converted first from engine `float` value to Javascript `double` and then from `double` to `string` we can see that it is not rounded as expected because conversion from `float` to `double` adds these decimal digits:

```
0.33000001311302185
         **********
```

So, again, to prevent these rounding errors always use double in dashboard projects.

**Comment by fietser28** [comment]
> Please test the latest build and let me know if `'inf'` bug is fixed.

Tested it, it seems fixed. Thank you.

**Comment by fietser28** [comment]
Clear explanation. I also realise I'm not using (abusing) Math.round for numerical purposes but for displaying/formatting purposes. Is there a better alternative e.q.  sprintf("%2.2f", float) to control the float to string conversion?

**Comment by mvladic** [comment]
Yes, we should probably make string formatting function `String.format(...)` similar to `sprintf`.
