### ISSUE TITLE
Additional instrument connection types

### ISSUE THREAD

**Issue by prasimix** [eez-open/studio#28]
Support for Ethernet sockets, VXI, IVI, VISA interfaces/connections in needed. This is a generic topic that can be break up in new issues/tickets for better follow up. In general, we should use existing open source libraries. Here is short list of what is found so far:
* http://alexforencich.com/wiki/en/python-vxi11/start, https://github.com/python-ivi
* https://github.com/f4exb/libvxi11
* http://optics.eee.nottingham.ac.uk/vxi11/, https://github.com/applied-optics/vxi11
* https://metacpan.org/pod/Lab::VXI11, https://metacpan.org/pod/USB::TMC
* https://gist.github.com/pklaus/2597049 Controlling the Rigol DG1022 with Python on Linux (using the usbtmc driver) – Proof of Concept
* https://github.com/pyvisa/pyvisa (VISA)
* https://github.com/mabl/pyRigolWFM (VFM Viewer)
* https://github.com/Galvant/InstrumentKit (InstrumentKit: open source Python library, they also have an open source [GPIB-to-USB adapter](http://www.galvant.ca/#!/store), find discussion on EEVblog forum: [link1](https://www.eevblog.com/forum/buysellwanted/for-sale-oshw-gpibusb-adapter/), [link2]

**Comment by AndrewSmart** [comment]
At a glance through code you're not using VISA shared libraries right now?

Does the [ROHDE & SCHWARZ VISA shared library](https://www.rohde-schwarz.com/us/driver-pages/remote-control/3-visa-and-tools_231388.html) do everything you need?

They have a clause in their [license](https://scdn.rohde-schwarz.com/ur/pws/dl_downloads/dl_application/application_notes/1dc02___rs_v/RS_VISA_Terms_and_Conditions.pdf) speaking of third party open-source projects, it sounds like they wouldn't be opposed to distributing it with this GPLv3 project.

I didn't see any javascript libraries wrapping around the VISA shared library. So, can just make one with [SWIG](http://www.swig.org/Doc3.0/Javascript.html) I imagine.

I'd written a couple of these instrument session managers in-house for a lab, I used VISA to do it. I'm impressed with the bells and whistles you have in yours, like the calendar and notes. I never supported waveforms in my solutions either, but funding was cut off before I could do everything I wanted to anyway :-)

One different I took, is in scripting I translated the SCPI commands into the object oriented features of the language (MATLAB), so that auto-completion, validation (of ranges), context help, and other usefulness would be available within the IDE while writing scripts, e.g. Type:
```javascript
var instrument = bkprecision1.open();
instrument.volt.meas();  // a query
instrument.curr = 10; // a command
```

I was very happy to see your excellent work when browsing through the EEVblog Test Equipment forum threads when trying to help some chemists.

Oh, reading about the EEZ H24005 now, good work :-) Nevermind then about redistributing the R&S Visa shared library, I think you could just do a SWIG wrapper and have the user download it from R&S website themselves.

**Comment by mvladic** [comment]
Thanks Andrew for your input!

We will check ROHDE & SCHWARZ VISA shared library.

I think your idea to translate SCPI commands and queries to JavaScript object is brilliant. We know that we need to improve our scripting support and this will definitely be one of the ways to improve.

**Comment by prasimix** [comment]
Hi Andrew, this sounds promising, indeed. I took some time trying to establish connection with my Rigol DS1074S DSO but without success. I've tried it on Ubuntu 16.04LTS and Win7 (VBox VM). Here is the screenshot from the Win session:

![screenshot from 2019-01-27 16-34-38](https://user-images.githubusercontent.com/15106476/51803212-a0167600-2252-11e9-8df5-a44135e9ef74.png)

Do you have any idea why it doesn't work?

**Comment by prasimix** [comment]
Tested on an old notebook (Ubuntu 18.10) that has _old_ USB hub, and it works! I have to find out what is going on with TCP (Ethernet) connection.

![screenshot from 2019-01-27 16-54-19](https://user-images.githubusercontent.com/15106476/51803398-12885580-2255-11e9-95e0-098ba630ab48.png)

**Comment by AndrewSmart** [comment]
> I think your idea to translate SCPI commands and queries to JavaScript object is brilliant. We know that we need to improve our scripting support and this will definitely be one of the ways to improve.

Thank you, I guess you don't have to. I think you might be able to get autocompletion/suggestions working in the editor without translating the instrument SCPI protocol into OO structures. I've used [autocomplete in YUI3](https://yuilibrary.com/yui/docs/autocomplete/) before to pop up a listbox, along the lines of what Intellisense does:
![listbox OO autocomplete example](https://raw.githubusercontent.com/wiki/Microsoft/TypeScript/images/decl1.png)

But YUI3 is deprecated and I know other newer javascript libraries will do the same thing.

One difficulty I had in algorithmically translating SCPI into OO structures is occasionally an instrument used unusual language, like a colon in a weird place. Or "standard" commands/queries of a single line on one instrument were composed of multiple commands on a different instrument due to some overhead commands (e.g. mandatory error checking? other odd stuff), so I'd hide that overhead within the OO interface so things were more "uniform" between instruments.

The first one I made was in C++ & wxWidgets, using a tab per instrument (using wxAUI within wxWidgets), tabs could be dragged between windows around much like modern browsers:
![Tabs example](https://trac.wxwidgets.org/raw-attachment/ticket/13079/WxWidgets.jpg)
Within the sidebar, the entire protocol for the active tab was available as GUI widgets (categorized into maybe 4 categories). Within this sidebar would be buttons for connection/disconnection. Unfortunately I don't have a screenshot of what I made.

But, this was an academic group/lab I was writing this for, so there was a problem with maintainability, so I moved over into Matlab and had the benefit of scripting autocomplete within their IDE. Designing a GUI was a bit limited on that platform, but at least future academics/students could more easily pick up the work and use it for whatever ends.

I believe in the C++ case I wrapped around the "ANSI-C in LabWindows/CVI" VISA library flavor, and I expect that would be best here with javascript. I can get around to doing this eventually in EEZ Studio if you don't, while I also add support for the Mooshimeter. They use some [unusual protocol](https://moosh.im/wiki/index.php/BLE_Serial_Protocol_Description) over bluetooth LE. I guess I can just SWIG wrap around [this library](https://github.com/ghtyrant/libsooshi) (hmmm... I wish they'd just used SCPI over the BLE Serial Port Profile, oh well).

**Comment by ochococo** [comment]
Hey guys, I'm new here 👋 

Maybe someone already mentioned it, but just to be sure, have you seen this wrapper:

https://github.com/petertorelli/ni-visa

Seems like something we could use to add support for VISA.

I'm still trying to figure out how the studio works under the hood so I'm not able to do that myself just yet.

WDYT @mvladic @prasimix ?

**Comment by prasimix** [comment]
Hi @ochococo, it seems like a wrapper for NI VISA, that is huge and Windows only. We'd like to proceed with R&H VISA that looks more promising.

**Comment by ochococo** [comment]
Not Windows only. There is also a Mac (darwin) implementation and it works like a charm. 
I don't think it would hurt anyone to have the NI VISA support but you're the boss here. 
I hope it works out with the ROHDE & SCHWARZ VISA🤞 Cheers!
