### ISSUE TITLE
How to adapt to new gui engine and new platform

### ISSUE THREAD

**Issue by xlbao123** [eez-open/studio#293]
Very inspiring project.
I would like to use this as a designer for another gui engine, and a hardware platform for my own products. And I would like to add layout features and attributes. I'm not sure how much work it would be to do this, could you offer some suggestions?

**Comment by mvladic** [comment]
Although Studio supports different project types for different GUI engines (LVGL, EEZ-GUI and Dashboard), for now we have no plans to document how it is done. 
If you want to integrate another GUI engine as a new project type, then you should check how LVGL is integrated. 
The most complicated part of the integration was rendering LVGL widgets within the studio. There we used the LVGL library which we compiled with emscripten so that it can be executed within the web browser environment. 
In the case of the EEZ-GUI engine integration, which we did long before LVGL, we reimplemented the rendering itself in JavaScript using the HTML Canvas API. If we can choose now, we would do the same thing as for LVGL.
