### ISSUE TITLE
question: basic scpi logging graphing?

### ISSUE THREAD

**Issue by tablatronix** [eez-open/studio#35]
Sorry to post questions here, could not find a support resource

This project looks amazing, but I cannot figure out how/if I can just do basic logging and graphing of basic scpi, say DMM `val1?` time based logging and graphing, or a PS v/a etc

I was just testing GDM8251a in scpi terminal for starters.

Am I misunderstanding this apps capability, or do I have maybe write js as an action and save to dataset then graph waveforms?

Close if not allowed.

**Comment by prasimix** [comment]
Thanks for your question. So far we've tested "logging" of our power supply (i.e. EEZ H24005) and Rigol DSO/MSO. Since logging is usually returns a huge stream of data some kind of manipulation/processing is required to store them in database and make ready for graphing. In general if SCPI query return string that starts with # Studio will recognize it as a "log data" and try to display that "item" as a graph.
Please note that project is under heavy development, and we are working toward releasing [M2](https://github.com/eez-open/studio/milestone/1) version possibly next month. We are still focused on basic infrastructure that should also allows one to simply add new so-called _instrument extension_ that could come with predefined scripts to make various actions. 
Please stay tuned about new release here and I'll post updates on the [EEVblog forum](http://www.eevblog.com/forum/testgear/eez-studio-for-accessing-your-(scpi)-instruments/).
