### ISSUE TITLE
[Dashboard] throwError: Execution queue is full

### ISSUE THREAD

**Issue by dong-king** [eez-open/studio#473]
**Describe the bug**
When i run my dashboard project, an error is thrown: Execution queue is full.

![image](https://github.com/user-attachments/assets/a07d89ee-c453-44ec-9746-6a88a3faccb0)

When I deleted some components, the error disappeared.

Is this because I use too many widget and action components in my project?

**Comment by mvladic** [comment]
Yes, the reason could be that you have too many widgets. Or some logical error inside your flow. For example, if you have some loop in your flow where inside the loop there is an action which has two outputs and execution continue from both outputs simultaneously and execution from these outputs both run in a loop - basically doubles execution flow for each loop iteration execution. The first reason (too many widget) can be easily fixed and will be fixed in the HF version. The second reason must be fixed in the flow.

**Comment by mvladic** [comment]
This is an example of the flow that will inevitably result in "Execution queue is full":

![image](https://github.com/user-attachments/assets/4b9b7dab-1c66-4847-8f69-a60df3716cd5)

**Comment by mvladic** [comment]
Max. queue size for dashboard is increased from 1000 to 100000.
