### ISSUE TITLE
[LVGL] Possibly a bug. Missing #include <string.h> statement

### ISSUE THREAD

**Issue by gwiethaus** [eez-open/studio#522]
**Bug**

The #include <string.h> declaration is missing in the ui.c file due to the strcmp() function in the generated code:

```
static const void *getLvglImageByName(const char *name) {
    for (size_t imageIndex = 0; imageIndex < sizeof(images) / sizeof(ext_img_desc_t); imageIndex++) {
        if (strcmp(images[imageIndex].name, name) == 0) {
            return images[imageIndex].img_dsc;
        }
    }
    return 0;
}
```

**Screen:**

![01](https://github.com/user-attachments/assets/c2b9145d-7fbf-4004-9ac4-3b078880c3df)

![02](https://github.com/user-attachments/assets/b65c210b-e3e7-4b6f-ae47-1e0d7529529d)

**Desktop:**
 - OS: Windows 10
 - Library: LVGL 9.2.0
 - Visual Studio Code 1.90.2
 - Platformio: Core 6.1.15, Home 3.4.4
 - EEZ Studio 0.16.0

**Comment by mvladic** [comment]
Added `#include <string.h>` in the `ui.c` for the projects that doesn't use EEZ Flow - because, only for those project there is a `strcmp` in `ui.c`.

Please note that only newly created project will have this include, for projects created before user needs to manually add it in `ui.c` file tamplate in project settings:

![image](https://github.com/user-attachments/assets/eb838c97-600f-4f87-87fc-aba439f3207d)
