### ISSUE TITLE
When importing the file into Code::Blocks to simulate LVGL, two types of errors may occur.

### ISSUE THREAD

**Issue by LOIC-MIKA** [eez-open/studio#549]
**Describe the bug**
ui\eez-flow.cpp|5384|error: expected ')' before 'PRId32'|
ui\eez-flow.cpp|5427|error: cast from 'void*' to 'uint32_t' {aka 'unsigned int'} loses precision [-fpermissive]|

**To Reproduce**
Only the EEZ Studio files compile successfully in Code::Blocks; the EEZ-Flow files do not.

**Expected behavior**
Port the EEZ Studio simulation of LVGL to the STM32H743IIT6.

**Screenshots**
![f85e7fee61197bae5f1ca547a288afb](https://github.com/user-attachments/assets/547df956-0972-4f84-b0f2-c28f0b4a0e88)

Windows11

** LVGL version (if used)**
- 8.x

**Comment by mvladic** [comment]
Which version of GCC compiler you have? Here is what I have:

![image](https://github.com/user-attachments/assets/2cf22bd7-642a-4205-a703-43c1c70581c7)

`PRId32` and `PRIu32` should be defined in `#include <inttypes.h>`, and it is on above GCC compiler.

With my version of GCC there is only one error with the Studio 0.16.1:

![image](https://github.com/user-attachments/assets/fcddd09f-a3b4-40df-88b8-35928aa97da3)

This error I already fixed in the master branch - this will be released by next Monday as version 0.17.0.

Here is the fix for this error. Instead of:

```
int32_t userData = (int32_t)lv_event_get_user_data(event);
```

it should be:

```
    void *userDataPointer = lv_event_get_user_data(event);
    int32_t userData = *((int32_t*)(&userDataPointer));
```
