### ISSUE TITLE
[LVGL] Pages not visible with User Widget

### ISSUE THREAD

**Issue by FourLeafTec** [eez-open/studio#593]
**Describe the bug**
Pages not visible with User Widget in LVGL project

**To Reproduce**
1. Create Project with LVGL template, chose LVGL version 9.x
2. Create User Widget `T1`
3. Add `Label:Text` to `T1`
4. Add T1 to Main
5. Click `Run`, Page is empty.

**Screenshots**
<img width="843" alt="截屏2024-10-16 18 54 40" src="https://github.com/user-attachments/assets/c46fa9d1-28fa-4d7f-b3bb-7d8f7379b4ef">

<img width="843" alt="截屏2024-10-16 18 54 51" src="https://github.com/user-attachments/assets/cb681c3f-ebd8-45c0-8766-eb25b61468c6">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 14.6.1 (23G93)

** LVGL version**

-  9.x

**Additional context**
The test eez-project file:

[lvgl.zip](https://github.com/user-attachments/files/17394564/lvgl.zip)

**Comment by mvladic** [comment]
This is a bug! 

This problem is only present for the LVGL projects **without Flow support**:

![image](https://github.com/user-attachments/assets/a964a7dc-dda1-4038-b0f3-9e113d9c73ca)

![image](https://github.com/user-attachments/assets/2e124a74-ea6b-43dd-9599-c6cfd1430243)

Also, this problem manifest only when previewing the screen using Studio Simulator (when you press the Run button), but your generated code (with the Build button) should work.
