### ISSUE TITLE
How to change a group to another group ?

### ISSUE THREAD

**Issue by liriyao** [eez-open/studio#625]
version 0.19 
I found group index ,but don't found a way to use it to change to another group. Which action shoud i use?
![image](https://github.com/user-attachments/assets/8188533e-8a18-4ea3-bbfd-cfe8a574dc22)

**Comment by mvladic** [comment]
There is no such action in LVGL action. You need that from the code. The reason why there is no such action is because Studio doesn't manage input devices that can exists in your target project. But, studio exports all defined groups and they are declared in `screens.h`, like this:

![image](https://github.com/user-attachments/assets/5a422456-3153-4182-a1cd-1588f1d83438)

So, you can change the group for the particular input device by using:

```
#include "ui/screens.h"

lv_indev_t *my_encoder_indev;

lv_indev_set_group(my_encoder_indev, groups.encoder_group);
```

**Comment by liriyao** [comment]
thanks
